### PR TITLE
Swap `package.json`'s `bsconfig.json` entry for `rescript.json`

### PR DESCRIPTION
**Pull request by cwstra**
What it says on the tin; noticed it when I couldn't build after using a fork.

### CODE REVIEW

**Comment by cometkim** [comment]
Good catch.

Maybe it would be better to publish both `rescript.json` and `bsconfig.json` with the same content for compatibility

**Comment by cwstra** [comment]
Per @tsnobip [in the PR which initially renamed the file](https://github.com/rescript-lang/rescript-react/pull/112), looks like the current version of the library is incompatible with versions <11 anyways?

**Comment by cometkim** [comment]
Yes. So, we need to copy content and maintain it for a while

**Review by cknitt — APPROVED** [review]
Thanks, good catch!

**Pull request merged**
