### PR TITLE
Version 0.11.0-rc.2

### PR DESCRIPTION
**Pull request by cknitt**

### CODE REVIEW

**Review by cristianoc — APPROVED** [review]

**Comment by cristianoc** [comment]
@mattdamon108 how about another round of testing, with compiler and rescript-react both rc.2
That should be the only thing left for the 10.1 compiler

**Comment by mattdamon108** [comment]
Sure, I'll run tests and share the result. 1) v3 backward compatibility 2) v4 classic & automatic.
I'm going to focus on the test of v3 backward compatibility.

**Comment by cristianoc** [comment]
> Sure, I'll run tests and share the result. 1) v3 backward compatibility 2) v4 classic & automatic.
> I'm going to focus on the test of v3 backward compatibility.

Great, then we can ask again on the forum, with simplified instructions now that everything is published to npm.

**Comment by mattdamon108** [comment]
deps

`package.json`
```
"rescript-relay": "0.0.0-connection-id-maker-fix-24be613b",
"@rescript/react": "^0.11.0-rc.2",
"rescript": "^10.1.0-rc.2",
```

---

V3

`bsconfig.json`
```
"jsx": {
    "version": 3,
    "v3-dependencies": [
      "rescript-relay"
    ]
  }
"bsc-flags": [
    "-open ReactV3"
  ]
```
I've tested on the current production project, it builds successfully without any code change.

---

V4 classic & automatic

```
"jsx": {
    "version": 4,
  }
"bsc-flags": [
    "-open ReactV3"
  ]
```
Everything seems fine, except for the below breakings in the case of a component key.
```rescript
let key = Some("k")
let _ = <C ?key /> // option<string> vs. string
```

**Comment by mattdamon108** [comment]
Side comment: there would be dependencies that are not supported in v4, it would break it.
For example, having a `React.Context.Provider` component or using old React binding e.g. `ReactDOM.Experimental`

**Comment by cristianoc** [comment]
Why should the type of 'key' change?
Is that by design, or just a consequence of how things are set up?

**Comment by mattdamon108** [comment]
https://github.com/rescript-lang/rescript-react/blob/master/src/React.res#L17:L21
If change the `k: option<string>`, then it gets worse.
```rescript
let _ = <C key=Some("k") />
```

**Comment by cristianoc** [comment]
Isn't key a special case in the ppx already? By treating it as a special prop it should be possible to make it type string.

**Comment by mattdamon108** [comment]
```rescript
%%private(
  @inline
  let addKeyProp = (p: 'props, ~k: option<string>=?): 'props =>
    switch k {
    | Some(k) =>
      Obj.magic(Js.Obj.assign(Obj.magic(p), {"key": k}))
    | None => p
    }
)
```
How about this?

**Comment by cristianoc** [comment]
If it removes the breaking change, it sounds good.
Was ?key possible in V3, or does it become a new possibility?

**Comment by mattdamon108** [comment]
> Was ?key possible in V3, or does it become a new possibility?

Yes, it was possible.

**Comment by mattdamon108** [comment]
> ```rescript
> %%private(
>   @inline
>   let addKeyProp = (p: 'props, ~k: option<string>=?): 'props =>
>     switch k {
>     | Some(k) =>
>       Obj.magic(Js.Obj.assign(Obj.magic(p), {"key": k}))
>     | None => p
>     }
> )
> ```
> 
> How about this?

It works well. I'll make a PR.

**Comment by mattdamon108** [comment]
#74

**Comment by mattdamon108** [comment]
https://github.com/rescript-lang/syntax/pull/693

**Pull request merged**
