### PR TITLE
Deprecate ReactDOM.props & compat to JSX v4 lowercase

### PR DESCRIPTION
**Pull request by mattdamon108**
This PR deprecates the `type ReactDOM.props`, and bind the `type ReactDOM.domProps` to `JsxDOM.domProps`.
Also, it will change the ReactDOM.createElement* bindings to make compatible with JSX v4 lowercase.

### CODE REVIEW

**Comment by mattdamon108** [comment]
https://github.com/rescript-lang/rescript-react/pull/63/commits/23389412e3918eb23b3f7b87cdac1aacd3b5bcbe for `aria*` attributes of DOM element makes avoiding the OCaml expression `#_true`.

**Comment by cknitt** [comment]
The domProps type variables thing needs to be reverted again now that we decided in #5706 not to do it.

**Comment by mattdamon108** [comment]
> The domProps type variables thing needs to be reverted again now that we decided in #5706 not to do it.

Done!

**Review by cknitt — APPROVED** [review]

**Comment by cristianoc** [comment]
Merge away

**Comment by mattdamon108** [comment]
> Merge away

Merged

**Pull request merged**
