### PR TITLE
Make React binding in zero cost

### PR DESCRIPTION
**Pull request by mattdamon108**
https://github.com/rescript-lang/rescript-react/issues/76

### CODE REVIEW

**Comment by mattdamon108** [comment]
Maybe ignore bs.js from version control as before?

**Review by cknitt — DISMISSED** [review]

**Comment by cknitt** [comment]
> Maybe ignore bs.js from version control as before?

I think it's good to keep .bs.js in source control in this project so that we notice unexpected changes there (like things suddenly being not zero cost anymore) more easily.

**Comment by cknitt** [comment]
Also, good to see this change in the compiler in this PR:

```
/* react Not a pure module */
```

->

```
/* No side effect */
```

👍

**Comment by mattdamon108** [comment]
> Also, good to see this change in the compiler output in this PR:
> 
> ```
> /* react Not a pure module */
> ```
> 
> ->
> 
> ```
> /* No side effect */
> ```
> 
> (and nothing being exported anymore but the empty submodules) 👍

Indeed!

**Review by cknitt — APPROVED** [review]

**Review by cristianoc — APPROVED** [review]

**Pull request merged**
