### PR TITLE
Jsx adaptions

### PR DESCRIPTION
**Pull request by ryyppy**

### CODE REVIEW

**Comment by cknitt** [comment]
@ryyppy I guess this is obsolete and can be closed?

**Comment by cknitt** [comment]
@ryyppy @mattdamon108 Is there anything still relevant in this PR or can it be closed?

**Comment by mattdamon108** [comment]
I think JSX v4 has already a transformation using `_jsx` with bindings.

**Comment by cknitt** [comment]
Ok, so I am closing this one now.

**Pull request closed without merging**
